scene:
  name: "Default Scene"
  entities:
    - name: "Camera"
      transform:
        position: { x: 0.0, y: 0.0, z: 5.0 }
        rotation: { x: 0.0, y: 0.0, z: 0.0 }
        scale: { x: 1.0, y: 1.0, z: 1.0 }
      camera:
        fov: 45.0
        nearPlane: 0.1
        farPlane: 100.0
    - name: "Cube"
      transform:
        position: { x: 0.0, y: 0.0, z: 0.0 }
        rotation: { x: 0.0, y: 0.0, z: 0.0 }
        scale: { x: 1.0, y: 1.0, z: 1.0 }
      mesh:
        file: "assets/models/cube.obj"
      material:
        ambient: { x: 0.1, y: 0.1, z: 0.1 }
        diffuse: { x: 0.7, y: 0.7, z: 0.7 }
        specular: { x: 1.0, y: 1.0, z: 1.0 }
        shininess: 32.0
